package com.safar.listing.entity.enums;

public enum InteriorProjectStatus {
    CONSULTATION_BOOKED, MEASUREMENT_DONE, DESIGN_IN_PROGRESS, DESIGN_APPROVED,
    MATERIAL_SELECTED, QUOTE_APPROVED, EXECUTION, QC_IN_PROGRESS, COMPLETED, CANCELLED
}
