package com.safar.listing.entity.enums;

public enum SalePropertyType {
    // Residential
    APARTMENT, INDEPENDENT_HOUSE, VILLA, PLOT, PENTHOUSE,
    STUDIO, BUILDER_FLOOR, FARM_HOUSE, ROW_HOUSE,
    // Commercial
    COMMERCIAL_OFFICE, COMMERCIAL_SHOP, COMMERCIAL_SHOWROOM,
    COMMERCIAL_WAREHOUSE, INDUSTRIAL,
    // Land (new)
    RESIDENTIAL_PLOT, AGRICULTURAL_LAND, FARMING_LAND,
    COMMERCIAL_LAND, INDUSTRIAL_LAND
}
