package com.safar.listing.entity.enums;

public enum SalePropertyType {
    APARTMENT, INDEPENDENT_HOUSE, VILLA, PLOT, PENTHOUSE,
    STUDIO, BUILDER_FLOOR, FARM_HOUSE, ROW_HOUSE,
    COMMERCIAL_OFFICE, COMMERCIAL_SHOP, COMMERCIAL_SHOWROOM,
    COMMERCIAL_WAREHOUSE, INDUSTRIAL
}
