-- V18: Host verification trust system, anti-fraud, enhanced KYC fields

ALTER TABLE profiles ADD COLUMN IF NOT EXISTS verification_level VARCHAR(20) DEFAULT 'UNVERIFIED';
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS trust_score INTEGER DEFAULT 0;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS host_type VARCHAR(30) DEFAULT 'INDIVIDUAL';
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS resident_status VARCHAR(10) DEFAULT 'RESIDENT';
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS monthly_payout_cap_paise BIGINT DEFAULT 1000000;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS fraud_risk_score INTEGER DEFAULT 0;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS selfie_verified BOOLEAN DEFAULT FALSE;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS digilocker_verified BOOLEAN DEFAULT FALSE;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS verification_expires_at TIMESTAMPTZ;
