package com.safar.listing.dto;

import com.safar.listing.entity.enums.*;
import jakarta.validation.constraints.*;

import java.math.BigDecimal;
import java.util.List;

public record CreateListingRequest(
        @NotBlank String title,
        @NotBlank String description,
        @NotNull ListingType type,
        CommercialCategory commercialCategory,
        @NotBlank String addressLine1,
        String addressLine2,
        @NotBlank String city,
        @NotBlank String state,
        @NotBlank @Pattern(regexp = "\\d{6}") String pincode,
        @NotNull BigDecimal lat,
        @NotNull BigDecimal lng,
        @NotNull @Min(1) Integer maxGuests,
        Integer bedrooms,
        Integer bathrooms,
        Integer totalRooms,
        List<String> amenities,
        @NotNull @Min(100) Long basePricePaise,
        PricingUnit pricingUnit,
        Integer minBookingHours,
        Boolean instantBook,
        Boolean gstApplicable,
        String gstin,
        Boolean petFriendly,
        Integer maxPets,
        @Min(1) @jakarta.validation.constraints.Max(5) Integer starRating,
        CancellationPolicy cancellationPolicy,
        MealPlan mealPlan,
        List<String> bedTypes,
        List<String> accessibilityFeatures,
        Boolean freeCancellation,
        Boolean noPrepayment,
        String checkInFrom,
        String checkInUntil,
        String checkOutFrom,
        String checkOutUntil,
        Boolean childrenAllowed,
        ParkingType parkingType,
        Boolean breakfastIncluded,
        Integer areaSqft,
        String operatingHoursFrom,
        String operatingHoursUntil,
        Boolean aashrayReady,
        Integer aashrayDiscountPercent,
        Long longTermMonthlyPaise,
        Integer minStayDays,
        String floorPlanUrl,
        String panoramaUrl,
        String videoTourUrl,
        String neighborhoodPhotoUrls,
        Integer weeklyDiscountPercent,
        Integer monthlyDiscountPercent,
        Long cleaningFeePaise,
        Integer visibilityBoostPercent,
        // PG/Co-living fields
        String occupancyType,
        String foodType,
        String gateClosingTime,
        Integer noticePeriodDays,
        Long securityDepositPaise,
        String depositType,
        String depositTerms,
        Integer gracePeriodDays,
        Integer latePenaltyBps,
        // Insurance
        Boolean insuranceEnabled,
        Long insuranceAmountPaise,
        String insuranceType,
        // Hotel fields
        String hotelChain,
        Boolean frontDesk24h,
        String checkoutTime,
        String checkinTime,
        // Wizard-provided room types (PG/COLIVING) — skips default seed when non-empty
        List<RoomTypeRequest> roomTypes
) {}
