package com.safar.booking.entity.enums;

public enum CancellationReason {
    GUEST_CHANGE_OF_PLANS,
    GUEST_FOUND_ALTERNATIVE,
    GUEST_MEDICAL_EMERGENCY,
    GUEST_TRAVEL_CANCELLED,
    GUEST_PRICE_TOO_HIGH,
    HOST_PROPERTY_UNAVAILABLE,
    HOST_MAINTENANCE_ISSUE,
    HOST_DOUBLE_BOOKED,
    HOST_PERSONAL_REASON,
    PAYMENT_FAILED,
    PAYMENT_TIMEOUT,
    SYSTEM_AUTO_EXPIRED,
    OTHER
}
